In [6]:
import os

print(os.getcwd())

C:\Users\palch\OneDrive\Documents\OneDrive\Desktop\Customer_Shopping_Behavior_Analysis\notebooks

In [7]:
import pandas as pd

df = pd.read_csv(r'C:\Users\palch\Downloads\customer_shopping_behavior_dataset.csv')

df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,58,Male,Dress,Clothing,51,Louisiana,M,White,Winter,4.0,Yes,Express,Yes,Yes,13,Cash,Annually
1,2,56,Male,Heels,Footwear,73,Louisiana,XL,Gold,Winter,4.4,Yes,Store Pickup,No,No,17,Cash,Fortnightly
2,3,66,Female,Sweater,Clothing,68,Rhode Island,L,Green,Summer,4.5,No,2-Day Shipping,Yes,Yes,24,Venmo,Annually
3,4,36,Female,Sandals,Footwear,25,Georgia,M,Violet,Winter,4.6,Yes,Next Day Air,No,No,40,Credit Card,Fortnightly
4,5,41,Female,Boots,Footwear,29,Florida,M,Olive,Spring,3.7,No,Store Pickup,Yes,Yes,43,Credit Card,Weekly

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             1000 non-null   int64
 1   Age                     1000 non-null   int64
 2   Gender                  1000 non-null   object
 3   Item Purchased          1000 non-null   object
 4   Category                1000 non-null   object
 5   Purchase Amount (USD)   1000 non-null   int64
 6   Location                1000 non-null   object
 7   Size                    1000 non-null   object
 8   Color                   1000 non-null   object
 9   Season                  1000 non-null   object
 10  Review Rating           1000 non-null   float64
 11  Subscription Status     1000 non-null   object
 12  Shipping Type           1000 non-null   object
 13  Discount Applied        1000 non-null   object
 14  Promo Code Used         1000 non-null   object
 15  Previous Purchases      1000 non-null   int64
 16  Payment Method          1000 non-null   object
 17  Frequency of Purchases  1000 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 140.8+ KB

In [9]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,1000.000000,1000.000000,1000,1000,1000,1000.000000,1000,1000,1000,1000,1000.000000,1000,1000,1000,1000,1000.000000,1000,1000
unique,NaN,NaN,2,23,4,NaN,25,4,17,4,NaN,2,6,2,2,NaN,6,6
top,NaN,NaN,Female,Coat,Clothing,NaN,California,XL,Blue,Fall,NaN,No,Standard,Yes,Yes,NaN,Cash,Fortnightly
freq,NaN,NaN,522,101,273,NaN,53,267,66,260,NaN,519,175,519,740,NaN,196,176
mean,500.500000,44.420000,NaN,NaN,NaN,59.903000,NaN,NaN,NaN,NaN,3.759100,NaN,NaN,NaN,NaN,25.478000,NaN,NaN
std,288.819436,15.050253,NaN,NaN,NaN,23.091965,NaN,NaN,NaN,NaN,0.697843,NaN,NaN,NaN,NaN,14.707543,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,250.750000,32.000000,NaN,NaN,NaN,40.000000,NaN,NaN,NaN,NaN,3.200000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,500.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,750.250000,57.000000,NaN,NaN,NaN,80.000000,NaN,NaN,NaN,NaN,4.300000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,1000.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [10]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [11]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [13]:
df = df.rename(columns={ 'purchase_amount_(usd)': 'purchase_amount'})

In [14]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [15]:
#create a column age_group 
labels = ['Young Adult','Adult','middle-aged','senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [16]:
df[['age','age_group']].head(10)

   age    age_group
0   58       senior
1   56  middle-aged
2   66       senior
3   36        Adult
4   41        Adult
5   32  Young Adult
6   65       senior
7   45  middle-aged
8   47  middle-aged
9   19  Young Adult

In [17]:
# purchase_frequency_days

frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [18]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                      365               Annually
1                       14            Fortnightly
2                      365               Annually
3                       14            Fortnightly
4                        7                 Weekly
5                       14            Fortnightly
6                       14              Bi-Weekly
7                       14            Fortnightly
8                       90              Quarterly
9                       90              Quarterly

In [19]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1               No              No
2              Yes             Yes
3               No              No
4              Yes             Yes
5               No             Yes
6              Yes             Yes
7               No             Yes
8              Yes             Yes
9              Yes             Yes

In [20]:
(df['discount_applied'] == df['promo_code_used']).all()

np.False_

In [21]:
!pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\palch\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in c:\users\palch\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\palch\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\palch\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [27]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = "swapna@mysql1"
host = "localhost"
port = "3306"
database = "shopping_analysis"

engine = create_engine(
    f"mysql+pymysql://{root}:{quote_plus(swapna@mysql1)}@{localhost}:{3306}/{shopping_analysis}"
)

table_name = "my_table"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

df_read = pd.read_sql(
    "SELECT * FROM my_table LIMIT 5;",
    engine
)

df_read

NameError: name 'root' is not defined

In [29]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "root"
password = "swapna@mysql1"
host = "localhost"
port = "3306"
database = "shopping_analysis"

engine = create_engine(
    f"mysql+pymysql://{username}:{quote_plus(password)}@{host}:{port}/{database}"
)

table_name = "my_table"

df.to_sql(
    table_name,
    engine,
    if_exists="replace",
    index=False
)

df_read = pd.read_sql(
    "SELECT * FROM my_table LIMIT 5;",
    engine
)

df_read

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,58,Male,Dress,Clothing,51,Louisiana,M,White,Winter,4.0,Yes,Express,Yes,Yes,13,Cash,Annually,senior,365
1,2,56,Male,Heels,Footwear,73,Louisiana,XL,Gold,Winter,4.4,Yes,Store Pickup,No,No,17,Cash,Fortnightly,middle-aged,14
2,3,66,Female,Sweater,Clothing,68,Rhode Island,L,Green,Summer,4.5,No,2-Day Shipping,Yes,Yes,24,Venmo,Annually,senior,365
3,4,36,Female,Sandals,Footwear,25,Georgia,M,Violet,Winter,4.6,Yes,Next Day Air,No,No,40,Credit Card,Fortnightly,Adult,14
4,5,41,Female,Boots,Footwear,29,Florida,M,Olive,Spring,3.7,No,Store Pickup,Yes,Yes,43,Credit Card,Weekly,Adult,7

In [30]:
df.to_sql(
    "my_table",
    engine,
    if_exists="replace",
    index=False
)

1000